# Generated by Django 5.0.8 on 2024-08-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Notes', 'verbose_name_plural': 'Notes'},
        ),
    ]
